name: Build Android SO
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build with ndk-build
        run: |
          ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-so-files
          path: libs/
          
